services:
  deepglycansite:
    build:
      context: DeepGlycanSite
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./shared_data
        target: /app/DeepGlycanSite/workflow_data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks: 
      - mol_dock_network

networks:
  mol_dock_network:
    driver: bridge